"""Regenerate atlas/confusables.py from Unicode's confusables.txt (UTS #39).

    curl -sSLO https://www.unicode.org/Public/security/latest/confusables.txt
    python3 tools/atlas/gen_confusables.py confusables.txt > tools/atlas/atlas/confusables.py

Kept: single non-ASCII source characters whose prototype is printable ASCII (Cyrillic,
Greek, fullwidth, mathematical and other look-alikes of Latin letters, digits and
punctuation). That is what look-alike identifiers in logs use, and it keeps atlas
stdlib-only with a small table.
"""

import sys


def main(path: str) -> None:
    version = date = ""
    table = {}
    for line in open(path, encoding="utf-8-sig"):
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        if line.startswith("# Date:"):
            date = line.split(":", 1)[1].strip()
        if not line.strip() or line.startswith("#"):
            continue
        src, dst = [x.strip() for x in line.split(";")[:2]]
        if " " in src:
            continue
        s = chr(int(src, 16))
        t = "".join(chr(int(x, 16)) for x in dst.split())
        if ord(s) < 128 or not all(32 < ord(c) < 127 for c in t):
            continue
        table[ord(s)] = t
    print('"""Look-alike characters: non-ASCII character -> the ASCII text it imitates.')
    print()
    print("Generated by tools/atlas/gen_confusables.py from Unicode confusables.txt (UTS #39),")
    print(f"version {version}, {date}. {len(table)} entries. Do not edit by hand.")
    print('"""')
    print()
    print("CONFUSABLES = {")
    items = sorted(table.items())
    for k in range(0, len(items), 6):
        print("    " + " ".join(f"{cp}: {t!r}," for cp, t in items[k : k + 6]))
    print("}")


if __name__ == "__main__":
    main(sys.argv[1])
